### ISSUE TITLE
Progress bar percentage color dark theme?

### ISSUE THREAD

**Issue by nexus2001** [maboroshin/qBittorrentDarktheme#21]
Can you change progress bar percentage color in next update? Yellow perhaps?
This is how it looks now on dark theme:

![progress](https://user-images.githubusercontent.com/9553081/103354397-b4e98d00-4aab-11eb-8f41-95fdd5937ea1.jpg)

Also checkbox should have ✓ as a check mark, looks better.
And icons far above should have a bit brighter color:
![icons](https://user-images.githubusercontent.com/9553081/103354585-393c1000-4aac-11eb-8bdf-a29fbeab3e05.jpg)

**Comment by maboroshin** [comment]
@nexus2001 
The progress bar can be changed. Took a while to identify. I finished.

Icon change is under investigation.

Which checkbox? [RIght click menu is can't change](https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591917158).

**Comment by nexus2001** [comment]
Checkbox in "content" part. Where you download something and you can select what will be downloaded and what not.

**Comment by GREYWOLF1013** [comment]
> @nexus2001
> The progress bar can be changed. Took a while to identify. I finished.
(https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591917158).
What setting was changed for the color of the progress bar? I don't like the current color and would like to change it for myself

**Comment by maboroshin** [comment]
@GREYWOLF1013
Color changes require compilation. Please read README.md . 

If you understand CSS, you can change it below. 

src/stylesheet.qss: QProgressBar

However, the current Rev9 inherits the default settings. So even if you change here, the shape will be broken.

I am currently parsing so that it can be set from the value of QProgressBar.  This has been successful.

Please wait for Rev10.

**Comment by maboroshin** [comment]
@GREYWOLF1013 : What color do you want? Light, dark, blue, red. I apply a color theme. Sometimes it's hard to see the text due to a color.

**Comment by GREYWOLF1013** [comment]
@maboroshin I was just going to switch it back to the light blue that was present before 4.3.0

**Comment by maboroshin** [comment]
@nexus2001 : I've adjusted the icons.
I don't know how to change the checkbox. Also, I think the current checkbox is good.

@GREYWOLF1013 : Rev10 has been released.

I think it's a good idea to improve the bar.
But I don't know how to revert to former bar. Also, I can't build a former bar.
If someone makes a great bar, I want to use it.

**Comment by jagannatharjun** [comment]
> But I don't know how to revert to former bar. Also, I can't build a former bar.

remove QProgressBar changes from stylesheet

**Comment by maboroshin** [comment]
@jagannatharjun 

If I use the same file as qBittorrent ver4.2.3 with the light blue bar, it get dark bar in ver4.3.0.

Even if I delete the ```QProgressBar```, the dark is still inherited. So I want to specify a new ```QProgressBar```, but I don't know how. probably get something similar by specifying ```qlineargradient```.

**Comment by jagannatharjun** [comment]
> @jagannatharjun
> 
> If I use the same file as qBittorrent ver4.2.3 with the light blue bar, it get dark bar in ver4.3.0.
> 
> Even if I delete the `QProgressBar`, the dark is still inherited. So I want to specify a new `QProgressBar`, but I don't know how. probably get something similar by specifying `qlineargradient`.

https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qprogressbar

to specify gradient
```css
/* linear gradient from white to green */
QTextEdit {
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                stop:0 white, stop: 0.4 gray, stop:1 green)
}

/* linear gradient from white to green */
QTextEdit {
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                stop:0 white, stop: 0.4 rgba(10, 20, 30, 40),
                stop:1 rgb(0, 200, 230, 200))
}

/* conical gradient from white to green */
QTextEdit {
    background: qconicalgradient(cx:0.5, cy:0.5, angle:30,
                stop:0 white, stop:1 #00FF00)
}

/* radial gradient from white to green */
QTextEdit {
    background: qradialgradient(cx:0, cy:0, radius: 1,
                fx:0.5, fy:0.5, stop:0 white, stop:1 green)
}
```

**Comment by maboroshin** [comment]
@jagannatharjun : Thank you.
I'll experiment. Making the exact same bar sees to be difficult. Or, I want to make it a little darker.

**Comment by maboroshin** [comment]
**Original**
![image](https://user-images.githubusercontent.com/41102508/103562428-6a7a6d00-4efe-11eb-9b77-3fdfef7e6303.png)

**Rev10 (ICEBURG)**
![image](https://user-images.githubusercontent.com/41102508/103562773-f9878500-4efe-11eb-8dab-1b34930c88a7.png)

**My work1**
![image](https://user-images.githubusercontent.com/41102508/103562330-3901a180-4efe-11eb-873b-5ca09b9d28a8.png)
```css
QProgressBar {
  background-color: #002B36;
  color: #dadada;
  border : none;
  text-align: center;
  font: bold;
}

QProgressBar::chunk {
  background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                      stop:0 #2179c3, stop:0.5 #1d86e9, stop:1 #2179c3);
  border : 1px solid #469be0;
  border-radius: 2px ;
  margin: 1px;
}
```

**My work2**
![image](https://user-images.githubusercontent.com/41102508/103562083-d7d9ce00-4efd-11eb-949e-7b728de78a0c.png)
```css
QProgressBar {
  background-color: #002B36;
  color: #839496;
  border : none;
  text-align: center;
  font: bold;
}

QProgressBar::chunk {
  background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                      stop:0 #0c0f1d, stop:0.5 #1f415c, stop:1 #0c0f1d);
  border : 1px solid #586E75 ;
  border-radius: 2px ;
  margin: 1px ;
}
```

**Comment by maboroshin** [comment]
**My work 3**
![image](https://user-images.githubusercontent.com/41102508/103846243-04017480-50e1-11eb-9d1a-6409a7c8f869.png)

```css
QProgressBar {
  margin: 2px 0 0;
  background: qlineargradient(x1:0, y1:0, x2:0, y2:0,
                                      stop:0 #2c2c2c, stop:1 #363636);
  color: #dadada;
  border-top: 1px solid #191919 ;
  border-bottom: 1px solid #6c6c6c ;
  border-left: 1px solid #1d1e20 ;
  border-right: 1px solid #434343 ;
  border-radius: 7px ;

  text-align: center;
  font: bold;
}

QProgressBar::chunk {
  background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                      stop:0 #a3b1cf, stop:0.2 #557198, stop:1 #334760);
  border : 1px solid #111111;
  border-radius: 7px ;
}
```

**My work4**
![image](https://user-images.githubusercontent.com/41102508/103846793-4bd4cb80-50e2-11eb-92bf-16dc9943e275.png)

```css
QProgressBar {
  margin: 2px 0 0;
  background: qlineargradient(x1:0, y1:0, x2:0, y2:0,
                                      stop:0 #2c2c2c, stop:1 #363636);
  color: #dadada;
  border-top: 1px solid #191919 ;
  border-bottom: 1px solid #6c6c6c ;
  border-left: 1px solid #1d1e20 ;
  border-right: 1px solid #434343 ;
  border-radius: 2px ;

  text-align: center;
  font: bold;
}

QProgressBar::chunk {
  background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                      stop:0 #e3ec91, stop:0.1 #3c752c, stop: 0.9 #3c752c, stop:1 #779414);
  border : 1px solid #111111;
  border-radius: 2px ;
}
```

**My work5**
![image](https://user-images.githubusercontent.com/41102508/103847152-ec2af000-50e2-11eb-8451-2f92630ef8c5.png)
```css
QProgressBar {
  margin: 2px 0 0;
  background: qlineargradient(x1:0, y1:0, x2:0, y2:0,
                                      stop:0 #2c2c2c, stop:1 #363636);
  color: #dadada;
  border-top: 1px solid #191919 ;
  border-bottom: 1px solid #6c6c6c ;
  border-left: 1px solid #1d1e20 ;
  border-right: 1px solid #434343 ;
  border-radius: 2px ; /* add */

  text-align: center;
  font: bold;
}

QProgressBar::chunk {
  background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                      stop:0 #3d9cc7, stop:0.1 #3a6dad, stop: 0.9 #3a6dad, stop:1 #101c3f);
  border : 1px solid #111111;
  border-radius: 2px ;
}
```

**Comment by maboroshin** [comment]
**My work6**
![image](https://user-images.githubusercontent.com/41102508/103847449-99056d00-50e3-11eb-85ec-8c838bc87b2b.png)

```css
QProgressBar {
  margin: 2px 0 0;
  background: #404040;
  color: #dadada;
  border-top: 1px solid #191919 ;
  border-bottom: 1px solid #3c3c3c ;
  border-left: 1px solid #1d1e20 ;
  border-right: 1px solid #434343 ;
  border-radius: 6px ;

  text-align: center;
  font: bold;
}

QProgressBar::chunk {
  background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                                      stop:0 #3d9cc7, stop:0.1 #3a6dad, stop: 0.9 #3a6dad, stop:1 #101c3f);
  border : 1px solid #111111;
  border-radius: 6px ;
}
```
